---
- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: install dependencies
    dnf:
     name: "{{ item }}"
    with_items:
    - git

  - name: updating system
    dnf:
     name: "*"
     state: latest
  - name: install squid proxy rpm
    dnf:
     name: squid
     state: latest
  - name: starting squid proxy service
    service:
     name: squid
     state: started
     enabled: yes
  - name: Backup the existing squid.conf file
    copy:
     src: /etc/squid/squid.conf
     dest: /etc/squid/squid.conf.bkp
     remote_src: yes

  - name: Downloading actual squid conf file
    git:
     repo: https://bitbucket.vficloud.net/scm/global/ansible.git
     dest: /etc/squid/conf
     update: yes
  - name: copy the squid conf file to default location
    copy:
     src: /etc/squid/conf/squid.conf
     dest: /etc/squid
     remote_src: yes
     

         
  - name: restart squid after replacing orig file
    service:
     name: squid
     state: restarted
     #- name: Perform heathcheck on squid service
     #curl:
     #url:
     #register: hc_output
     #failed_when: hc_output.rc != 0
